name: build for linux

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: check
      run: cargo check -j 20
    
    - name: install cross
      run: cargo install cross -j 20

    - name: build x64
      run: RUSTFLAGS='-C target-feature=+crt-static' cross build --release --locked -j 20 --target x86_64-unknown-linux-gnu
    
    - name: build x86
      run: RUSTFLAGS='-C target-feature=+crt-static' cross build --release --locked -j 20 --target i686-unknown-linux-gnu
    
    - name: build aarch64
      run: RUSTFLAGS='-C target-feature=+crt-static' cross build --release --locked -j 20 --target aarch64-unknown-linux-gnu
  
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@release-1.3
      env:
        GITHUB_TOKEN: ${{ secrets.TK }}
      with:
        releaseId: ${{ needs.create_release.outputs.id }}
        args: '*/sosistun'
        
